version: '3.9'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_pass"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  service:
    container_name: service
    tty: true
    build:
      context: .
    environment:
      - DB_USER=test_user
      - DB_PASS=test_pass
      - DB_NAME=test_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - SERVICE_PORT=:8080
      - SMTP_PRODUCER=azaabdranbayev@gmail.com
      - SMTP_TOKEN=
      - SMTP_HOST=smtp.gmail.com:587
      - SMT_NAME=smtp.gmail.com
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
